### ISSUE TITLE
Check is affected by page-level box-sizing: border-box;

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-checkbox#104]
It's common to have a global rule that sets box sizing:

```
* {
    box-sizing: border-box;
}
```

However, due to shady, this pierces into the local dom and affects the checkbox positioning:

<img width="159" alt="screen shot 2016-02-02 at 9 00 43 pm" src="https://cloud.githubusercontent.com/assets/238208/12773394/1c9cc378-c9f0-11e5-8014-969b2d1302ef.png">

One solution is to use `box-sizing: content-box;` on the checkbox.

**Comment by bicknellr** [comment]
We should (only) be able to assume the browser's default state. If we can't assume the browser's default state, then the best we could do would be to include an extremely specific 'CSS clear' in every element. (Effectively what `box-sizing: content-box;` would be doing.) Otherwise, all bets are off. If the user is using Polymer and adding styles outside of a `style is="custom-style"` tag before Shadow DOM and its associated style scoping are natively available then they should know that anything they apply globally does, in fact, apply globally - potentially breaking the assumptions of any components they use (Polymer or from another framework).

**Comment by ebidel** [comment]
Right, but this is a side effect of shady's lack of upper bound style encapsulation. It makes it challenging for users to use the component as advertised with a bit of debugging. I think we can a do folks a favor and ensure that the right default is set.

We also don't have a style hook for this element, so there's no way for users to style it.

**Comment by ebidel** [comment]
Unfortunately box-sizing also does not inherit :/

**Comment by notwaldorf** [comment]
related: https://github.com/PolymerElements/paper-elements/issues/55

**Comment by bicknellr** [comment]
The problem is that this argument applies to all CSS properties in all elements in the same way and implies that we have to normalize all properties in all elements. The only reasonable assumption that we could make about the environment is that it will not affect our elements at all. Otherwise, we are saying that some arbitrary and unknown subset of CSS properties have been changed. Learning this set and responding piecemeal would require JavaScript that would be more expensive than just loading a complete CSS normalization stylesheet. So, if we can't assume anything about our environment, we must reconstruct it completely to be sure we're not broken by it.

**Comment by bicknellr** [comment]
We could also go the paper-styles/typography route.. Use, but don't import, this normalization stylesheet in every element. If users are in a situation where their external stylesheets conflict, they could import it and all paper elements would reset based off of the single stylesheet.

**Comment by bicknellr** [comment]
(PolymerElements/paper-dialog-behavior#21 is related.)

**Comment by bicknellr** [comment]
Welp, after discussion with @notwaldorf, I concede that this argument is not worth it, so we're going ahead with #105. I still disagree though. :)
