### ISSUE TITLE
Read-only checkboxes ... toggles=false vs disabled ?

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-checkbox#51]
Using paper-checkboxes, I've hit a scenario where I would like to _sometimes_ ignore all user-input sent to a paper-checkbox. 

Reading the docs, `toggles=false` sounds like it might be what I'm looking for. However, I cannot get toggles to do anything most of the time. I'm able to prevent the user from checking an unchecked box (over in iron-button-state, active is always set to "false" whenever toggles is false) - inconsistently.

Is this how the toggles attribute should work?

`disabled` might really be what I'm looking for, instead... I just wanted some clarification on `toggles`

http://codepen.io/robrez/pen/MwmdRN?editors=100

**Comment by notwaldorf** [comment]
`toggles` means that the item can be pressed, but will never stay `active`. It's basically a normal button -- you click it and it always returns to its default state. A button with `toggles=true` will stay in itss `active` state after being pressed, and will return to its normal state after a second press.

If you want to ignore user input, you should set `disabled` on the `paper-checkbox` (setting `pointer-events: none` is weird because the checkbox looks clickable but isn't)

**Comment by robrez** [comment]
thanks
